language: python
python:
  - "3.5"
install:
  - "git fetch --unshallow --tags"
  - "pip install -r requirements.txt"
before_script: "cp api/config.yml.example api/config.yml"
script: "$(which doit) test"
