language: python
python:
  - "3.5"
install:
  - "git fetch --unshallow --tags"
  - "pip install -r requirements.txt"
before_script:
  - "cp autocert/api/config.yml.example autocert/api/config.yml"
script: "$(which doit) test"
