version: '2'
services:
    api:
        restart: always
        build: ./api
        expose:
          - "8000"
        volumes:
          - /usr/src/app/static
          - /var/tmp/auto-cert
        command: /usr/local/bin/gunicorn -w 2 -b :8000 main:app

    nginx:
        restart: always
        build: ./nginx
        ports:
          - "80:80"
        volumes:
          - /www/static
        volumes_from:
          - api
        links:
          - api:app
