version: '2'
services:
    api:
        network_mode: host
        restart: always
        build: ./api
        expose:
          - "8000"
        volumes:
          - /data/autocert:/data/autocert
        entrypoint: /usr/src/app/entrypoint.sh ${AC_USER} ${AC_UID}
    nginx:
        network_mode: host
        restart: always
        build: ./nginx
        ports:
          - "80:80"
        volumes_from:
          - api
        depends_on:
          - api
