version: '2'
services:
    api:
        network_mode: host
        restart: always
        build: ./api
        expose:
          - "8000"
        volumes:
          - /data/autocert:/data/autocert
        environment:
          - AC_UID=${AC_UID}
          - AC_GID=${AC_GID}
          - AC_USER=${AC_USER}
        entrypoint: /usr/src/app/entrypoint.sh
    nginx:
        network_mode: host
        restart: always
        build: ./nginx
        ports:
          - "80:80"
        volumes_from:
          - api
        depends_on:
          - api
