version: '2'
services:
    api:
        network_mode: host
        restart: always
        build: ./api
        expose:
          - "8000"
        volumes:
          - /data/autocert:/data/autocert
        command: python3 -u /usr/local/bin/gunicorn -t 120 -w 2 -b :8000 main:app
    nginx:
        network_mode: host
        restart: always
        build: ./nginx
        ports:
          - "80:80"
        volumes_from:
          - api
        depends_on:
          - api
